/**
 * Rental
 * The rental API description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChangePasswordDto { 
    id: string;
    email: string;
    firstname: string;
    lastname: string;
    role: string;
    status: string;
}
