/**
 * Test
 * Test API created by Integrated Technologies and Software Solutions, LLC --Sonny Saxton
 *
<<<<<<< HEAD
 * OpenAPI spec version: ITSS/v0.1
=======
 * OpenAPI spec version: 1.0
>>>>>>> 3656690318f4d09e142afc10214c71ea8d0d007f
 * Contact: sonny.saxton@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenDto { 
    expiresIn: number;
    accessToken: string;
}
