/**
 * Test
 * Test API created by Integrated Technologies and Software Solutions, LLC --Sonny Saxton
 *
 * OpenAPI spec version: 1.0
 * Contact: sonny.saxton@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserCmd { 
    id: string;
    email: string;
    firstname: string;
    lastname: string;
    password: string;
    role: string;
    status: string;
}
