/**
 * Test
 * Test API created by Integrated Technologies and Software Solutions, LLC --Sonny Saxton
 *
<<<<<<< HEAD
 * OpenAPI spec version: ITSS/v0.1
=======
 * OpenAPI spec version: 1.0
>>>>>>> 3656690318f4d09e142afc10214c71ea8d0d007f
 * Contact: sonny.saxton@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

<<<<<<< HEAD
import { Observable }                                        from 'rxjs';
=======
import { Observable }                                        from 'rxjs/Observable';
>>>>>>> 3656690318f4d09e142afc10214c71ea8d0d007f

import { GetProfileDto } from '../model/getProfileDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


<<<<<<< HEAD
@Injectable({
  providedIn: 'root'
})
export class ProfileService {

    protected basePath = 'http://localhost:49000/ITSS/v0.1';
=======
@Injectable()
export class ProfileService {

    protected basePath = 'http://localhost:49000/v0.1';
>>>>>>> 3656690318f4d09e142afc10214c71ea8d0d007f
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get user profile
     * Get get user profile from JWT payload.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProfile(observe?: 'body', reportProgress?: boolean): Observable<GetProfileDto>;
    public getProfile(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetProfileDto>>;
    public getProfile(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetProfileDto>>;
    public getProfile(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<GetProfileDto>(`${this.configuration.basePath}/profile`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
